### ISSUE TITLE
[beginner question] are git-fat files duplicated locally ?

### ISSUE THREAD

**Issue by mzemb** [cyaninc/git-fat#33] opened 2015-01-19 10:41 UTC
Hi.

I'm new to git-fat, and I'm testing it to handle binaries in my repo since it's seems a lot simplier than git-annex and well suited to my use-case. :)

After adding one file and pushing it to git-fat, I have two copies of it: once as the file itself and once in .git/fat/objects.

Is it a bug or did I miss something ?
If that behaviour is needed, could it be done with a symbolic link instead ?

Thanks,

Michael

**Comment by mzemb** [comment] 2015-01-19 12:19
Note: tested with 0.3.4 release (b651c8) and dev branch (57a0611).

**Comment by abraithwaite** [comment] 2015-01-19 17:45
It does make a full copy.  This is actually by design but there certainly could be an option for symlinks instead of copies.

**Comment by abraithwaite** [comment] 2015-01-19 17:58
I guess I should explain why it's by design: Some build processes don't like when files are symlinks and so they aren't.  Examples off the top of my head include javascript and web asset management (i.e. there are legitimate reasons to keep symlinks when rsyncing/packaging assets) and python's own packaging process has quirks when dealing with symlinks.

If you're interested, here's the two spots in the code which would have to change:
https://github.com/cyaninc/git-fat/blob/develop/git_fat/git_fat.py#L609-L623
https://github.com/cyaninc/git-fat/blob/develop/git_fat/git_fat.py#L639-L660

Aand, after reading that code again, it appears that it would be difficult.  Basically, if you were to make the file symlinked, then you wouldn't be able to use git filters.  Git filters depend on being able to tell when a file's changed so that it can update the index with the new file.

Perhaps an example:
```
/.git/fat/objects
/path/to/binary.bin
```
Since `.git/fat/objects` exists outside of the git tree, it would be more difficult to tell when that file's been changed.  More importantly, if you copy a file elsewhere to the same spot (updating), it will be copied to the untracked objects directory.  That would be bad because it overwrites the existing object which you may or may not have pushed.

So in review, it's not impossible but it may be difficult to implement.

**Comment by CzarekTomczak** [comment] 2015-01-20 09:00
Symlinks are not a good idea on Windows, there are issues with them. Git for example doesn't support symlinks on Windows.

I don't see anything wrong with the current design. Git also keeps a copy of all your files, but in a different format. This is a version control system. I don't see how you could not keep duplicate copies. This is supposed to be an extension to Git, so it must support Git features: restoring deleted files, keep full history, allow different copies of file in different branches  etc. So it must keep copies of the files in the .git/ folder.

**Comment by CzarekTomczak** [comment] 2015-01-20 09:06
Ahh, I typed too fast and didn't think it throughly ;-) The files are also stored on the server.. I also didn't read the full post by Alan, which explain clearly the implementation difficulties. Nothing to add.

**Comment by mzemb** [comment] 2015-01-20 11:10
Thanks Alan for the detailled explanation.

To sum up the internal working, please tell me if I'm wrong:

1) git-fat maintains a copy of the files it stores on the server in .git/fat/objects, which communicate with the server when I run git-fat-pull or git-fat-push with a simple copy from/to.

2) on git-add (or git-checkout), git-fat run its filters function (respectively clean and smudge), to produce or decode the file name through sha1 hashing. The content of the file is then copied to/from .git/fat/objects with the new name but the same content.

3) to avoid having two copies of files locally, git-fat code could be changed in order to use the files on the server as a reference instead of .git/fat/objects, but it's not a minor change. (And it may have consequences on the usage I'm not yet aware of).

**Comment by abraithwaite** [comment] 2015-01-20 16:18
Correct on all points.  The one thing that I'd add to 3 is that it would be necessary to ensure that if a file git fat manages gets changed and it's a symlink, you'd need to update where the symlink points to in the filters.  This is challenging because the filters don't run when you do things like `mv` or `cp`.  They only run on a subset of git commands.

**Comment by abraithwaite** [comment] 2015-01-30 16:18
Going to close this, but eventually I'd like to aggregate things tagged with question into an FAQ. :-)

**Closed by abraithwaite** 2015-01-30 16:18 UTC
Labels: question
